// Temporary Data until we connect with Firebase

export default tempData = [
  {
      title: 'Month 1',
      imageURL:"https://upload.wikimedia.org/wikipedia/commons/1/1f/Pregnancy_test_result.jpg",
      text: "Congratulations, you are pregnant!  I’m sure there are millions of things going on in your head right now about your pregnancy and having your child.\n\n This app is here to help you keep track of something very important on your pregnancy journey; your nutrition. Now, you are not just eating to sustain yourself, there is a little life inside you that you need to take into consideration. Everything that you eat, the baby is eating too! That is why there are a number of things you should avoid as soon as you find out you are pregnant. \n\n Foods to avoid: \n - Unpasteurised dairy \n - Pate \n - Soft Blue Cheese \n - Alcohol cold cured meats \n - Raw shellfish \n - Liver \n - Raw or undercooked meat.\n\n You also need to make sure you are getting enough of these essential nutrients: \n -Folic Acid \n -Calcium \n -Vitamin D \n -Iron \n -Omega 3.\n\n A pregnancy-specific multivitamin should contain the recommended amount of these nutrients so it is a good idea to start taking one right away.\n\n  While now is certainly not the time to be thinking about losing weight it is important to note that you are not now “eating for two”. Being pregnant certainly does not mean you should double what you are eating! It is important that you are getting enough calories from healthy sources to nourish your body and your growing baby but this does not mean that you can now eat whatever you like.\n\n Maintaining a healthy weight during pregnancy is important to prevent complications such as gestational diabetes, joint problems, hypertension, and will ensure you have a better chance of smooth delivery and a healthy baby.\n\n To calculate what your caloric intake should be during each trimester you can check out the handy calculator. You will notice that your calory intake should not increase in the first trimester, and only very slightly in the second and third trimesters. You should enter the appropriate amount of calories for you in the app each day and keep a log of what you are eating to ensure you sticking to the recommendations."
  },
  {
      title: "Month 2",
      imageURL: 'https://cdn.pixabay.com/photo/2017/08/01/23/22/hands-2568594_1280.jpg',
      text: "Welcome to month 2 of your pregnancy! By now you may be getting over the initial shock and excitement of finding out you are pregnant and, unfortunately for some of you, this is when some of those not-so-nice pregnancy symptoms will start to kick in.\n\n For many women morning sickness starts to kick in around week 6. Despite the name, morning sickness can be an all-day thing for many and can cause women to feel nauseous, have strong aversions to food, and even vomit. If you are experiencing morning sickness it may feel difficult to get the right amount of nutrients into you every day. Eating small amounts often is a good way to combat morning sickness and eating dry bland foods such as toast or plain crackers or cereal helps many women.\n\n It is especially important to keep track of your calorie intake if you are experiencing morning sickness as a healthy weight gain during pregnancy is important for your growing baby.\n\n How much weight should you gain during pregnancy?\n If you have a healthy BMI, the recommendation is to gain 1 pound per week. If you are overweight, this should only be half a pound per week. If you are underweight you may be advised to gain more than 1 pound per week. To calculate your BMI to see how much weight you should be gaining, check out the BMI calculator."
  },
  {
      title: "Month 3",
      imageURL: "https://p1.pxfuel.com/preview/70/630/547/girl-woman-sleeping-tired-bed-sheets.jpg",
      text: "Welcome to month 3 of your pregnancy! By now you may be very familiar with one of the most common 1st-trimester symptoms: tiredness!\n\n The vast majority of women feel very tired during this first part of their pregnancy, but you are growing a human, so cut yourself a little slack! For many, just getting up, going to work and coming home can be exhausting! While reaching for the coffee may have been your go-to solution of fatigue in the past, it may be a good idea to cut back a little now.\n\n Too much caffeine is not good for you or your baby and very high levels can cause your baby to have a low birth weight. It is recommended that you limit your caffeine intake to 200mg per day which is about 2 mugs of instant coffee or 3 cups of tea. Unfortunately chocolate also contains caffeine, so you will want to limit your consumption.\n\n If you are looking for a pick me up without caffeine, protein-rich foods provide you with the kind of energy that keeps you going to fill up on eggs, lean meat, and nuts and seeds."
  },
  {
      title: "Month 4",
      imageURL: "https://images.pexels.com/photos/1646716/pexels-photo-1646716.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      text: "Welcome to the second trimester! Congratulations Mama, you have made it this far, we know it hasn’t been easy. The good news is that many women repost the second trimester as being the most enjoyable. Morning sickness has already peaked any may be subsiding substantially, you will start to see some of that energy come back and you might even be starting to get a cute little bump!\n\n Now that you are in your second trimester your calorie intake will increase slightly. You can revisit the pregnancy calorie calculator to remind yourself what your new recommendation is. Remember to enter your new daily calorie intake into the app when you start your day.\n\n Now that morning sickness is subsiding you may find it easier to get al of your calories in each day. Here are a few examples of 200 calorie snacks you can add to your daily diet to help fuel your body and your growing baby:\n-A small bowl of porridge\n-A fruit smoothie\n-Half of a chicken salad\n-Wholegrain toast with cottage cheese"
  },
  {
      title: "Month 5",
      imageURL: 'https://live.staticflickr.com/4159/34192445141_4052dd0723_b.jpg',
      text: "Welcome to month 5! By now you will probably have a little bump that people can notice. This is a wonderful time in your pregnancy and the fact that your baby will be with you in a few short months is getting more and more real!\n\n While keeping track of your calorie intake in this app is a fantastic way to avoid excess weight gain in pregnancy, getting some light exercise will also help a lot. Pregnancy-safe exercises not only help to reduce unhealthy weight gain but can also help with your cardiovascular health, muscle tone, and mental health.\n\n Here are some examples of fantastic exercises to incorporate into your daily routine:\n- Swimming\n-Walking\n-Pregnancy Yoga\n-Pregnancy Pilates\n\n As you get bigger your back may be under pressure from your growing baby. Now would be a great time to treat yourself to a massage!"
  },
  {
      title: "Month 6",
      imageURL: 'https://storage.needpix.com/rsynced_images/pregnant-1438139_1280.jpg',
      text: "Welcome to month 6! This is the last month of your second trimester and if you are planning on getting a pregnancy photo shoot done, this is a perfect time! You have a lovely bump at this stage, are not too tired and many women experience glowing skin and shiny hair at this point in their pregnancy.\n\n As you progress in your pregnancy it is important to remember to take extreme care with the food you are easting to ensure it is safe for you and your baby. Food poisoning in pregnancy can be very dangerous.\n\n Here are some ways to take extra care with food preparation during pregnancy:\n- Do not eat food that is out of date\n- Keep raw and cooked foods separate\n- Wash your hands before and after food preparation\n- Make sure all meat, fish, and eggs are cooked thoroughly\n- Wash all fruit and vegetables very well before eating"
  },
  {
      title: "Month 7",
      imageURL: 'https://p1.pxfuel.com/preview/29/819/830/mother-belly-sunset-pregnant-woman.jpg',
      text: "Welcome to your third trimester, congratulations you are nearly there! Now that you are in the final trimester your calorie intake should increase slightly. As a reminder, you can check out the pregnancy calorie calculator and enter in the appropriate daily amount of calories in the app.\n\n You have made it this far in your journey and you may be feeling tired and ready to throw in the towel with this whole healthy eating thing. While the occasional treat here and there won’t do any harm it is important to stay on track with your healthy eating to give your baby the best start possible to life. Keep going Mama you are nearly there!\n\n Here are some healthy snacks that you can add to your day to get to your calorie goal:\n- 6 oz. container sweetened yogurt and 1/2 cup granola. Calories: 300\n- 1/2 cup Greek yogurt with 1 tbsp. honey and 1 tbsp. chopped nuts/seeds/dried fruit/chia or flax Calories: 300\n- 1 chicken drumstick and 1/2 cup mashed potato. Calories: 400\n- Hummus, pita bread, carrots, cheddar cheese. Calories: 240\n- Honey wheat pretzels, apple wedges, grapes, cheddar cheese. Calories: 200"
  },
  {
      title: "Month 8",
      imageURL: 'https://cdn.pixabay.com/photo/2017/05/11/19/44/fruit-2305192_1280.jpg',
      text: "Welcome to month 8 - not long to go now until your baby is in your arms. You have done so well eating healthily for you and your baby, keep at it!\n\n By now your bump is probably quite substantial and you may feel like giving in to those pesky pregnancy cravings or treating yourself to some not-so-healthy foods. While the occasional indulgence is ok, you don’t want to be making a daily habit of it, not now that you are so close to the finish line.\n\n Here are some swaps you can make to satisfy your cravings while staying healthy:\n\n- Crisps  >\nBreadsticks, dry cereal, rice cakes or crunchy vegetable sticks\n\n- Cakes  >\nEnglish muffins with a little unsaturated spread\n\n- Sweets >\nDried fruit such as raisins, dried apricots or dried figs\n\n- Pizza  >\nWholegrain pitta bread dipped in reduced-fat hummus\n\n- Chocolate >\nA banana or some chunks of fresh pineapple\n\n- Ice cream >\nLow fat yogurt or rice pudding"
  },
  {
      title: "Month 9",
      imageURL: 'https://i2.pickpik.com/photos/491/898/331/bebe-child-pregnant-woman-boy-preview.jpg',
      text: "You made it to the last month, congratulations! In a few short weeks, you will be holding your healthy baby in your arms. This last month is often one of the most difficult for women. You are now carrying a fully-grown baby ( who will keep growing until the day you deliver) around with you everywhere you go. Not to mention the extra weight from water retention, extra-blood supply, and the placenta. This last month may be tough but it will be all worth it!\n\n Right about now many women complain of painful heartburn. This is due to the additional pressure on your stomach caused by your baby. Most women see heartburn disappear completely in once they have their baby but in the meantime here are a few foods we recommend to reduce it.\n- Ginger: Ginger has natural anti-inflammatory properties, and it’s a natural treatment for heartburn and other gastrointestinal problems.\n- Oatmeal is whole grain, and an excellent source of fiber. A diet high in fiber has been linked with a lower risk of acid reflux.\n- Noncitrus fruits: Noncitrus fruits, including melons, bananas, apples, and pears, are less likely to trigger reflux symptoms than acidic fruits.\n- Egg whites. Stay away from egg yolks, though, which are high in fat and may trigger reflux symptoms.\n\n Now that you are in the final month of pregnancy, keep going with logging your calorie intake daily, and keep active. This will ensure you gain the right amount of weight, will have an easier delivery, and will have less weight to lose once your baby is born.\n\n Good luck in these finals weeks we hope you have found our app useful for staying healthy and we wish you all the best with your new baby!"
  }
];
